version: 2
jobs:
  build:nodejs:
    docker: 
      - image: node:12.20.1
    environment:
      ENVIRONMENT: development
    steps:
      - checkout
      - run: |
          cd frontend && yarn && yarn build
          ls -la
      - store_artifacts:
          path: frontend/build
  build:golang:
    docker: 
      - image: golang:1.15.7
    environment:
      ENVIRONMENT: development
    steps:
      - checkout
      - run: |
          apt update && apt install -y libwebkit2gtk-4.0-dev
          unset GOPATH
          go build main.go
      - store_artifacts:
          path: main
          
workflows:
  version: 2
  build:
    jobs:
      - build:nodejs
      - build:golang:
          requires:
            - build:nodejs
