version: 2
jobs:
  build:nodejs:
    docker: 
      - image: node:12.20.1
    environment:
      ENVIRONMENT: development
    steps:
      - run: |
          npm install --prefix frontend
          echo "[✔️] Initialization complete!"
          npm run build --prefix frontend
          echo "[✔️] Frontend build complete!"
      - store_artifacts:
          path: frontend/build
  build:golang:
    docker: 
      - image: golang:1.15.7
    environment:
      ENVIRONMENT: development
    steps:
      - run: |
          mkdir -p ./saas.app/Contents/MacOS
          go build -o ./saas.app/Contents/MacOS/saas
          echo "[✔️] Backend build complete!"
          
workflows:
  version: 2
  build:
    jobs:
      - build:nodejs
      - build:golang:
          requires:
            - build:nodejs
